trigger: none

pool:
  vmImage: ubuntu-latest
 
stages:
        
  - stage: Prod    
    jobs:
     - job: Final_Deployment
       pool: server
       steps:
#- script: echo This is the production deployement phase!
        - task: ServiceNow-DevOps-Server-Change-Acceleration@1
          inputs:
            connectedServiceName: 'dev257846-SG DevOps Project-ServiceNow DevOps Service Connection'
            changeRequestDetails: |
              {
                  "setCloseCode" : true,
                  "autoCloseChange" : true,
                  "attributes": {
                    "requested_by": {
                      "name": "Abel Tuter"
                    },
                    "start_date": "2025-01-05 08:00:00",
                    "end_date": "2025-01-08 08:00:00",
                    "cab_required": "yes",
                    "chg_model": {
                      "name": "DevOps"
                    },
                    "assignment_group": {
                      "name": "Analytics Settings Managers"
                    }
                  }
                }